"""Provider-neutral quant operator contracts."""

from oxq.operators.catalog import OperatorCatalog, load_operator_catalog
from oxq.operators.errors import (
    CausalityViolationError,
    ContractViolationError,
    DataFetchError,
    DependencyUnavailableError,
    DuplicateKeyError,
    InsufficientCrossSectionError,
    InsufficientHistoryError,
    InvalidManifestError,
    InvalidPanelError,
    InvalidParameterError,
    MissingColumnError,
    NumericalComputationError,
    OperatorError,
)
from oxq.operators.manifest import OperatorManifest, load_operator_manifest
from oxq.operators.panel import QuantPanelAdapter, validate_serialized_quant_panel
from oxq.operators.types import (
    FittedOperatorState,
    OperatorAvailability,
    OperatorCausality,
    OperatorContext,
    OperatorDiagnostics,
    OperatorLifecycle,
    OperatorProvenance,
    OperatorRequest,
    OperatorResult,
    OperatorScope,
    PriceAdjustment,
    QuantOperatorExecutor,
    TimestampSemantics,
)

__all__ = [
    "CausalityViolationError",
    "ContractViolationError",
    "DataFetchError",
    "DependencyUnavailableError",
    "DuplicateKeyError",
    "FittedOperatorState",
    "InsufficientCrossSectionError",
    "InsufficientHistoryError",
    "InvalidManifestError",
    "InvalidPanelError",
    "InvalidParameterError",
    "MissingColumnError",
    "NumericalComputationError",
    "OperatorAvailability",
    "OperatorCatalog",
    "OperatorCausality",
    "OperatorContext",
    "OperatorDiagnostics",
    "OperatorLifecycle",
    "OperatorManifest",
    "OperatorError",
    "OperatorProvenance",
    "OperatorRequest",
    "OperatorResult",
    "OperatorScope",
    "PriceAdjustment",
    "QuantOperatorExecutor",
    "QuantPanelAdapter",
    "TimestampSemantics",
    "load_operator_catalog",
    "load_operator_manifest",
    "validate_serialized_quant_panel",
]
