from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import click
import yaml  # type: ignore[import-untyped]

GENERATED_NOTICE = "<!-- generated by website/scripts/generate.py; do not edit by hand -->"


@dataclass(frozen=True)
class SkillSource:
    name: str
    description: str
    source_path: str


@dataclass(frozen=True)
class SkillExtension:
    title_zh: str
    summary_zh: str
    group: str
    use_cases_zh: tuple[str, ...]
    inputs_zh: tuple[str, ...]
    outputs_zh: tuple[str, ...]
    constraints_zh: tuple[str, ...]
    related_workflows: tuple[str, ...]


@dataclass(frozen=True)
class SkillRecord:
    source: SkillSource
    extension: SkillExtension


@dataclass(frozen=True)
class CommandRecord:
    path: str
    summary: str


class ContentError(ValueError):
    pass


def parse_skill_source(path: Path, repo_root: Path) -> SkillSource:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ContentError(f"{path} missing Skill front matter")

    parts = text.split("\n---\n", 1)
    if len(parts) != 2:
        raise ContentError(f"{path} missing closing Skill front matter delimiter")

    payload = yaml.safe_load(parts[0][4:]) or {}
    if not isinstance(payload, dict):
        raise ContentError(f"{path} Skill front matter must be a mapping")

    name = payload.get("name")
    description = payload.get("description")
    if not isinstance(name, str) or not name.strip():
        raise ContentError(f"{path} Skill front matter requires string name")
    if not isinstance(description, str) or not description.strip():
        raise ContentError(f"{path} Skill front matter requires string description")
    if path.parent.name != name:
        raise ContentError(f"{path} Skill directory name must equal front matter name")

    try:
        source_path = path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError as exc:
        raise ContentError(f"{path} is not under repository root") from exc

    return SkillSource(name=name, description=description, source_path=source_path)


def load_skill_sources(repo_root: Path) -> tuple[SkillSource, ...]:
    skill_paths = sorted((repo_root / "agent" / "skills").glob("*/SKILL.md"))
    sources = tuple(parse_skill_source(path, repo_root) for path in skill_paths)
    seen: set[str] = set()
    duplicates: set[str] = set()
    for source in sources:
        if source.name in seen:
            duplicates.add(source.name)
        seen.add(source.name)
    if duplicates:
        names = ", ".join(sorted(duplicates))
        raise ContentError(f"duplicate Skill names: {names}")
    return tuple(sorted(sources, key=lambda source: source.name))


def load_skill_extensions(path: Path) -> dict[str, SkillExtension]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    records = _extract_extension_records(payload, path)
    extensions: dict[str, SkillExtension] = {}
    for name, raw_extension in records:
        if name in extensions:
            raise ContentError(f"duplicate Chinese extension: {name}")
        extensions[name] = _parse_extension(name, raw_extension, path)
    return dict(sorted(extensions.items()))


def merge_skill_records(
    sources: tuple[SkillSource, ...],
    extensions: dict[str, SkillExtension],
) -> tuple[SkillRecord, ...]:
    source_names = {source.name for source in sources}
    extension_names = set(extensions)

    missing = sorted(source_names - extension_names)
    if missing:
        raise ContentError(f"missing Chinese extension: {', '.join(missing)}")

    orphan = sorted(extension_names - source_names)
    if orphan:
        raise ContentError(f"orphan Chinese extension: {', '.join(orphan)}")

    return tuple(
        SkillRecord(source=source, extension=extensions[source.name])
        for source in sorted(sources, key=lambda item: item.name)
    )


def collect_leaf_commands(root: click.Command) -> tuple[tuple[str, str], ...]:
    leaves: list[tuple[str, str]] = []

    def visit(command: click.Command, prefix: tuple[str, ...]) -> None:
        if isinstance(command, click.Group):
            for name, child in command.commands.items():
                visit(child, (*prefix, name))
            return
        path = " ".join(prefix)
        summary = command.help or command.short_help or ""
        leaves.append((path, summary.strip()))

    visit(root, ())
    return tuple(sorted(leaves, key=lambda item: item[0]))


def render_outputs(
    skills: tuple[SkillRecord, ...],
    commands: tuple[CommandRecord, ...],
) -> dict[Path, str]:
    sorted_skills = tuple(sorted(skills, key=lambda record: record.source.name))
    sorted_commands = tuple(sorted(commands, key=lambda record: record.path))
    outputs: dict[Path, str] = {
        Path("website/skills/index.md"): _normalize_text(_render_skills_index(sorted_skills)),
        Path("website/tools/index.md"): _normalize_text(_render_tools_index(sorted_commands)),
    }
    for skill in sorted_skills:
        outputs[Path("website/skills") / f"{skill.source.name}.md"] = _normalize_text(
            _render_skill_page(skill)
        )
    return outputs


def write_outputs(repo_root: Path, outputs: dict[Path, str]) -> None:
    for relative_path, text in sorted(outputs.items(), key=lambda item: item[0].as_posix()):
        if relative_path.is_absolute():
            raise ContentError(f"generated output path must be repo-relative: {relative_path}")
        target = repo_root / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(_normalize_text(text).encode("utf-8"))


def check_outputs(repo_root: Path, outputs: dict[Path, str]) -> None:
    messages: list[str] = []
    expected_paths = set(outputs)

    for relative_path, text in sorted(outputs.items(), key=lambda item: item[0].as_posix()):
        if relative_path.is_absolute():
            raise ContentError(f"generated output path must be repo-relative: {relative_path}")
        target = repo_root / relative_path
        expected_bytes = _normalize_text(text).encode("utf-8")
        if not target.exists():
            messages.append(f"missing generated file: {relative_path.as_posix()}")
            continue
        if target.read_bytes() != expected_bytes:
            messages.append(f"stale generated file: {relative_path.as_posix()}")

    for relative_path in _find_generated_markdown(repo_root):
        if relative_path not in expected_paths:
            messages.append(f"unexpected generated file: {relative_path.as_posix()}")

    if messages:
        detail = "; ".join(messages)
        raise ContentError(f"generated content drift: {detail}")


def _extract_extension_records(
    payload: object,
    path: Path,
) -> tuple[tuple[str, object], ...]:
    if isinstance(payload, dict):
        if "skills" in payload:
            skills_payload = payload["skills"]
            if isinstance(skills_payload, dict):
                return tuple(
                    _extension_record_from_mapping_item(name, raw, path)
                    for name, raw in skills_payload.items()
                )
            if isinstance(skills_payload, list):
                return tuple(_extension_record_from_list_item(item, path) for item in skills_payload)
            raise ContentError(f"{path} skills must be a mapping or list")
        return tuple(
            _extension_record_from_mapping_item(name, raw, path)
            for name, raw in payload.items()
        )
    if isinstance(payload, list):
        return tuple(_extension_record_from_list_item(item, path) for item in payload)
    raise ContentError(f"{path} must contain Skill extension records")


def _extension_record_from_mapping_item(
    name: object,
    raw_extension: object,
    path: Path,
) -> tuple[str, object]:
    if not isinstance(name, str) or not name.strip():
        raise ContentError(f"{path} Skill extension key must be a non-empty string")
    return name, raw_extension


def _extension_record_from_list_item(item: object, path: Path) -> tuple[str, object]:
    if not isinstance(item, dict):
        raise ContentError(f"{path} Skill extension list items must be mappings")
    name = item.get("name")
    if not isinstance(name, str) or not name.strip():
        raise ContentError(f"{path} Skill extension list item requires string name")
    return name, item


def _parse_extension(name: str, raw_extension: object, path: Path) -> SkillExtension:
    if not isinstance(raw_extension, dict):
        raise ContentError(f"{path} Chinese extension for {name} must be a mapping")
    return SkillExtension(
        title_zh=_required_string(raw_extension, "title_zh", name),
        summary_zh=_required_string(raw_extension, "summary_zh", name),
        group=_required_string(raw_extension, "group", name),
        use_cases_zh=_required_string_tuple(raw_extension, "use_cases_zh", name),
        inputs_zh=_required_string_tuple(raw_extension, "inputs_zh", name),
        outputs_zh=_required_string_tuple(raw_extension, "outputs_zh", name),
        constraints_zh=_required_string_tuple(raw_extension, "constraints_zh", name),
        related_workflows=_required_string_tuple(raw_extension, "related_workflows", name),
    )


def _required_string(payload: dict[Any, Any], key: str, name: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ContentError(f"empty Chinese field {key}: {name}")
    return value.strip()


def _required_string_tuple(payload: dict[Any, Any], key: str, name: str) -> tuple[str, ...]:
    value = payload.get(key)
    if not isinstance(value, list | tuple) or not value:
        raise ContentError(f"empty Chinese field {key}: {name}")
    items: list[str] = []
    for item in value:
        if not isinstance(item, str) or not item.strip():
            raise ContentError(f"empty Chinese field {key}: {name}")
        items.append(item.strip())
    return tuple(items)


def _render_skills_index(skills: tuple[SkillRecord, ...]) -> str:
    lines = [
        GENERATED_NOTICE,
        "# Agent Skills 索引",
        "",
        "这些页面由 `agent/skills/*/SKILL.md` 和 `website/data/skills.zh.yaml` 生成。",
        "",
    ]
    if not skills:
        lines.append("暂无 Skill 记录。")
        return "\n".join(lines)

    current_group: str | None = None
    for skill in skills:
        if skill.extension.group != current_group:
            current_group = skill.extension.group
            lines.extend(["", f"## {current_group}", ""])
        lines.extend(
            [
                f"### [{skill.extension.title_zh}](/skills/{skill.source.name})",
                "",
                skill.extension.summary_zh,
                "",
                f"- Canonical Skill: `{skill.source.name}`",
                f"- Source: `{skill.source.source_path}`",
                "",
            ]
        )
    return "\n".join(lines)


def _render_skill_page(skill: SkillRecord) -> str:
    extension = skill.extension
    source = skill.source
    lines = [
        GENERATED_NOTICE,
        f"# {extension.title_zh}",
        "",
        extension.summary_zh,
        "",
        "## Canonical Skill",
        "",
        f"- Name: `{source.name}`",
        f"- Source: `{source.source_path}`",
        f"- Description: {source.description}",
        "",
        "## 使用场景",
        "",
        *_bullet_lines(extension.use_cases_zh),
        "",
        "## 输入",
        "",
        *_bullet_lines(extension.inputs_zh),
        "",
        "## 输出",
        "",
        *_bullet_lines(extension.outputs_zh),
        "",
        "## 约束",
        "",
        *_bullet_lines(extension.constraints_zh),
        "",
        "## 关联工作流",
        "",
        *_bullet_lines(extension.related_workflows),
    ]
    return "\n".join(lines)


def _render_tools_index(commands: tuple[CommandRecord, ...]) -> str:
    lines = [
        GENERATED_NOTICE,
        "# CLI 工具索引",
        "",
        "这些命令来自 `oxq.cli.main.main` 的公开 Click 叶子命令树。",
        "",
    ]
    if not commands:
        lines.append("暂无 CLI 叶子命令。")
        return "\n".join(lines)

    for command in commands:
        lines.extend(
            [
                f"## `oxq {command.path}`",
                "",
                command.summary or "暂无命令说明。",
                "",
            ]
        )
    return "\n".join(lines)


def _bullet_lines(items: tuple[str, ...]) -> list[str]:
    return [f"- {item}" for item in items]


def _normalize_text(text: str) -> str:
    return text.rstrip("\n") + "\n"


def _find_generated_markdown(repo_root: Path) -> tuple[Path, ...]:
    roots = (repo_root / "website" / "skills", repo_root / "website" / "tools")
    generated: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.glob("*.md")):
            try:
                first_line = path.read_text(encoding="utf-8").splitlines()[0]
            except IndexError:
                continue
            if first_line == GENERATED_NOTICE:
                generated.append(path.relative_to(repo_root))
    return tuple(generated)
