"""Core data types for the engine pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import TYPE_CHECKING, Literal, Protocol, runtime_checkable

if TYPE_CHECKING:
    from oxq.portfolio.orderbook import ManagedOrder

import pandas as pd

# ---------------------------------------------------------------------------
# Value types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Order:
    """A trade order generated by a Rule.

    Order is an immutable request object. Rules generate Orders;
    the OrderRouter (e.g. SimBroker) receives and processes them.
    Order lifecycle state (open -> filled/canceled/expired) is
    tracked by the OrderBook, not on the Order itself.

    Attributes
    ----------
    symbol : str
        The ticker symbol to trade.
    side : Literal["BUY", "SELL"]
        Trade direction.
    shares : int
        Number of shares to trade.
    order_type : Literal["market", "limit", "stop", "stop_limit", "trailing_stop"]
        Order type. Default is "market".

        - ``"market"``: execute at current market price
        - ``"limit"``: execute at limit_price or better
        - ``"stop"``: trigger a market order when price hits stop_price
        - ``"stop_limit"``: trigger a limit order when price hits stop_price
        - ``"trailing_stop"``: stop price trails the market by trail_pct
    limit_price : Decimal or None
        Limit price for limit and stop_limit orders.
    stop_price : Decimal or None
        Stop trigger price for stop and stop_limit orders.
    trail_pct : float or None
        Trailing percentage for trailing_stop orders.
        E.g. 0.05 means the stop trails 5% below the high-water mark.
    """

    symbol: str
    side: Literal["BUY", "SELL"]
    shares: int
    currency: str = "CNY"
    order_type: Literal[
        "market", "limit", "stop", "stop_limit", "trailing_stop"
    ] = "market"
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    trail_pct: float | None = None


@dataclass(frozen=True)
class Fill:
    """A completed execution of an Order.

    Attributes
    ----------
    order : Order
        The original order that was filled.
    filled_price : Decimal
        Actual execution price (after slippage adjustment).
    filled_at : str
        ISO date string of fill time.
    fee : Decimal
        Transaction fee charged for this fill. Default is 0.
    """

    order: Order
    filled_price: Decimal
    filled_at: str
    fee: Decimal = Decimal("0")


@dataclass(frozen=True)
class Position:
    """A single holding in a portfolio.

    Attributes
    ----------
    symbol : str
        The ticker symbol.
    shares : int
        Number of shares held.
    avg_cost : Decimal
        Volume-weighted average cost per share.
    """

    symbol: str
    shares: int
    avg_cost: Decimal


@dataclass(frozen=True)
class PositionSnapshot:
    """Snapshot of a single position at a point in time.

    Attributes
    ----------
    shares : int
        Number of shares held.
    avg_cost : float
        Volume-weighted average cost per share.
    """

    shares: int
    avg_cost: float


@dataclass(frozen=True)
class BarSnapshot:
    """Per-bar portfolio snapshot for post-run analysis.

    Captured at the end of each bar in Engine.step().

    Attributes
    ----------
    date : pd.Timestamp
        Bar date with timezone.
    target_weights : dict[str, float]
        Raw optimizer output (before rules).
    adjusted_weights : dict[str, float]
        Weights after pre-trade rules adjustment.
    positions : dict[str, PositionSnapshot]
        Holdings after all fills for this bar.
    cash : float
        Cash balance after all fills and interest.
    total_value : float
        Total portfolio value (cash + positions).
    rule_reasons : dict[str, str]
        Pre-trade rule reasons keyed by symbol, with "__all__" for global holds.
    """

    date: pd.Timestamp
    target_weights: dict[str, float]
    adjusted_weights: dict[str, float]
    positions: dict[str, PositionSnapshot]
    cash: float
    total_value: float
    rule_reasons: dict[str, str] = field(default_factory=dict)


@dataclass
class Portfolio:
    """Mutable portfolio state tracking cash and positions.

    Attributes
    ----------
    cash : Decimal
        Available cash balance.
    positions : dict[str, Position]
        Current holdings keyed by symbol.
    """

    cash: Decimal
    currency: str = "CNY"
    positions: dict[str, Position] = field(default_factory=dict)
    bar_prices: dict[str, Decimal] = field(default_factory=dict)

    def total_value(self, prices: dict[str, Decimal]) -> Decimal:
        """Calculate total portfolio value (cash + positions)."""
        pos_value = sum(
            (pos.shares * prices.get(pos.symbol, Decimal("0"))
             for pos in self.positions.values()),
            Decimal("0"),
        )
        return self.cash + pos_value


@dataclass
class Constraint:
    """Per-symbol trade constraint applied by a Rule.

    Attributes
    ----------
    max_shares : int or None
        Maximum number of shares allowed.
    max_value : float or None
        Maximum notional value allowed.
    """

    max_shares: int | None = None
    max_value: float | None = None


@dataclass
class RuleResult:
    """Structured output returned by a Rule evaluation.

    Rules return a RuleResult to communicate weight overrides,
    per-symbol constraints, target positions, or a hold signal
    to the Engine pipeline.

    Attributes
    ----------
    weights : dict[str, float] or None
        Target weight overrides keyed by symbol.
    constraints : dict[str, Constraint] or None
        Per-symbol trade constraints.
    target_positions : dict[str, float] or None
        Absolute target positions keyed by symbol.
    hold : bool
        If True, freeze trading for this bar.
    reason : str
        Human-readable explanation for the rule action.
    """

    weights: dict[str, float] | None = None
    constraints: dict[str, Constraint] | None = None
    target_positions: dict[str, float] | None = None
    hold: bool = False
    reason: str = ""


# ---------------------------------------------------------------------------
# Execution protocols (Section 4.6 — three-protocol architecture)
# ---------------------------------------------------------------------------

@runtime_checkable
class OrderRouter(Protocol):
    """Order interface: the only exit point for strategy to submit orders."""

    def submit_order(self, order: Order) -> str: ...


@runtime_checkable
class FillReceiver(Protocol):
    """Fill interface: the only entry point for fills to reach the portfolio."""

    def get_fills(self) -> list[Fill]: ...


@runtime_checkable
class Broker(OrderRouter, FillReceiver, Protocol):
    """Unified broker protocol for Engine lifecycle management.

    Extends OrderRouter + FillReceiver with bar lifecycle hooks and
    order management methods. Engine depends only on this Protocol,
    not on concrete broker implementations.

    - ``on_bar_open`` — called at bar open (SimBroker: process pending orders)
    - ``on_bar_close`` — called at bar close (SimBroker: fill market orders)
    - ``get_open_orders`` / ``cancel_orders`` / ``cap_pending_sells`` —
      order book queries used by Engine for stale-order cleanup.
    """

    def on_bar_open(
        self, mktdata: dict[str, pd.DataFrame], date: pd.Timestamp,
    ) -> None: ...

    def on_bar_close(
        self, mktdata: dict[str, pd.DataFrame], date: pd.Timestamp,
    ) -> None: ...

    def get_open_orders(
        self, symbol: str | None = None,
    ) -> list[ManagedOrder]: ...

    def cancel_orders(
        self, symbol: str, side: str | None = None,
    ) -> list[ManagedOrder]: ...

    def cap_pending_sells(self, symbol: str, max_shares: int) -> None: ...


# ---------------------------------------------------------------------------
# Component protocols (Section 5.3-5.5)
# ---------------------------------------------------------------------------

@runtime_checkable
class Indicator(Protocol):
    """Indicator contract: pure function, per-symbol vectorized computation."""

    name: str

    def compute(self, mktdata: pd.DataFrame, **params: object) -> pd.Series: ...


@runtime_checkable
class Signal(Protocol):
    """Signal contract: per-symbol vectorized computation.

    Like Indicator, operates on a single symbol's DataFrame.
    Unlike Indicator (which outputs numerical values), Signal
    outputs trading intent: boolean or categorical labels.
    """

    name: str

    def compute(self, mktdata: pd.DataFrame, **params: object) -> pd.Series: ...


@runtime_checkable
class PortfolioOptimizer(Protocol):
    """Portfolio optimization contract.

    Takes signal output and indicator data, returns target weights.
    Weights must sum to 1.0 (including CASH).
    """

    name: str

    def optimize(
        self,
        signals: dict[str, pd.DataFrame],
        indicators: dict[str, pd.DataFrame],
    ) -> dict[str, float]: ...


@runtime_checkable
class Rule(Protocol):
    """Rule contract: bar-by-bar stateful evaluation.

    Pre-trade rules return RuleResult with weights/constraints.
    Post-trade monitoring rules return RuleResult with target_positions.
    """

    name: str

    def evaluate(
        self,
        symbol: str,
        row: pd.Series,
        portfolio: Portfolio,
        prices: dict[str, Decimal] | None = None,
    ) -> RuleResult: ...
