"""Core data types for the engine pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Protocol, runtime_checkable

import pandas as pd

# ---------------------------------------------------------------------------
# Value types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Order:
    """A trade order generated by a Rule."""

    symbol: str
    side: Literal["BUY", "SELL"]
    shares: int
    order_type: Literal["market"] = "market"


@dataclass(frozen=True)
class Fill:
    """A completed execution of an Order."""

    order: Order
    filled_price: float
    filled_at: str  # ISO date string


@dataclass(frozen=True)
class Position:
    """A single holding in a portfolio."""

    symbol: str
    shares: int
    avg_cost: float


@dataclass
class Portfolio:
    """Mutable portfolio state tracking cash and positions."""

    cash: float
    positions: dict[str, Position] = field(default_factory=dict)

    def total_value(self, prices: dict[str, float]) -> float:
        """Calculate total portfolio value (cash + positions)."""
        pos_value = sum(
            pos.shares * prices.get(pos.symbol, 0.0)
            for pos in self.positions.values()
        )
        return self.cash + pos_value


# ---------------------------------------------------------------------------
# Execution protocols (Section 4.6 — three-protocol architecture)
# ---------------------------------------------------------------------------

@runtime_checkable
class OrderRouter(Protocol):
    """Order interface: the only exit point for strategy to submit orders."""

    def submit_order(self, order: Order) -> str: ...


@runtime_checkable
class FillReceiver(Protocol):
    """Fill interface: the only entry point for fills to reach the portfolio."""

    def get_fills(self) -> list[Fill]: ...


# ---------------------------------------------------------------------------
# Component protocols (Section 5.3–5.5)
# ---------------------------------------------------------------------------

@runtime_checkable
class Indicator(Protocol):
    """Indicator contract: pure function, per-symbol vectorized computation."""

    name: str

    def compute(self, mktdata: pd.DataFrame, **params: object) -> pd.Series: ...


@runtime_checkable
class Signal(Protocol):
    """Signal contract: cross-sectional vectorized computation."""

    name: str

    def compute(
        self, mktdata: dict[str, pd.DataFrame], **params: object
    ) -> dict[str, pd.Series]: ...


@runtime_checkable
class Rule(Protocol):
    """Rule contract: bar-by-bar stateful evaluation."""

    name: str

    def evaluate(
        self, symbol: str, row: pd.Series, portfolio: Portfolio
    ) -> Order | None: ...
