from __future__ import annotations

import json
from pathlib import Path

import yaml


def test_report_chart_builder_skill_documents_chart_asset_workflow() -> None:
    skill = Path("agent/skills/report-chart-builder.md")

    text = skill.read_text(encoding="utf-8")

    assert "report-chart-builder" in text
    assert "discuss chart requirements" in text
    assert "plotting Python" in text
    assert "report_assets/figures" in text
    assert "report_assets/scripts" in text
    assert "oxq report asset add" in text
    assert "oxq report asset add-batch" in text
    assert "source_artifacts" in text
    assert "research_report.md" in text
    assert "research_report.html" in text
    assert "research-report-writer" in text
    assert "oxq report write" not in text
    assert "report_evidence.md" not in text
    assert "Do not modify metrics" in text
    assert "Do not modify audit" in text
    assert "CJK font" in text
    assert "default to English labels" in text
    assert "non-empty" in text
    assert "dimensions" in text
    assert "manifest" in text
    assert "Chart Applicability Matrix" in text
    assert "Violin Plot" in text
    assert "Pair Plot" in text
    assert "scan the run directory" in text
    assert "recommended chart set" in text


def test_report_chart_builder_skill_requires_professional_chart_pack() -> None:
    skill = Path("agent/skills/report-chart-builder.md")

    text = skill.read_text(encoding="utf-8")

    assert "Default Professional Chart Pack" in text
    assert "equity curve vs benchmark" in text
    assert "drawdown" in text
    assert "monthly return heatmap" in text
    assert "IS/OOS" in text
    assert "cost sensitivity" in text
    assert "parameter perturbation" in text
    assert "regime analysis" in text
    assert "position exposure" in text
    assert "trade PnL distribution" in text
    assert "message title" in text
    assert "source artifact" in text
    assert "caption" in text


def test_opencode_quant_reporter_can_write_html_and_report_assets() -> None:
    config = json.loads(Path("agent/opencode/opencode.json").read_text(encoding="utf-8"))

    write_permissions = config["agents"]["quant-reporter"]["permissions"]["write"]

    assert "runs/*/research_report.md" in write_permissions
    assert "runs/*/research_report.html" in write_permissions
    assert "runs/*/report_assets/**" in write_permissions
    assert "runs/*/report_evidence.md" not in write_permissions
    assert "report_write" not in config["agents"]["quant-reporter"]["tools"]


def test_opencode_bundle_references_single_source_skills() -> None:
    config = json.loads(Path("agent/opencode/opencode.json").read_text(encoding="utf-8"))

    assert config["skills"] == {"paths": ["agent/skills"]}
    canonical_skills = sorted(Path("agent/skills").glob("*.md"))
    assert canonical_skills
    for canonical in canonical_skills:
        skill_name = canonical.stem
        adapter = canonical.with_suffix("") / "SKILL.md"
        assert canonical.exists()
        assert adapter.exists()
        assert not adapter.is_symlink()
        canonical_meta = yaml.safe_load(canonical.read_text(encoding="utf-8").split("---", 2)[1])
        adapter_text = adapter.read_text(encoding="utf-8")
        adapter_meta = yaml.safe_load(adapter_text.split("---", 2)[1])
        assert adapter_meta["name"] == canonical_meta["name"]
        assert " ".join(adapter_meta["description"].split()) == " ".join(canonical_meta["description"].split())
        assert f"`../{skill_name}.md`" in adapter_text
        assert "must not copy full skill bodies" not in adapter_text
    assert not Path("agent/opencode/skills").exists()


def test_research_report_writer_skill_requires_agent_authored_final_report() -> None:
    skill = Path("agent/skills/research-report-writer.md")

    text = skill.read_text(encoding="utf-8")

    assert "research-report-writer" in text
    assert "research_report.md" in text
    assert "research_report.html" in text
    assert "render_markdown_html_report" in text
    assert "human researcher" in text
    assert "potential investor" in text
    assert "report_evidence.md" not in text
    assert "oxq report write" not in text
    assert "Do not invent evidence" in text
    assert "monthly returns" in text
    assert "positive/negative month counts" in text
    assert "artifact or facts API" in text
    assert "Mandatory Routing" in text
    assert "not a reason to bypass this skill" in text
    assert "write the report directly" in text
    assert "Chart Decision Gate" in text
    assert "ask the user whether report charts should be created" in text
    assert "If the user wants charts" in text
    assert "report-chart-builder" in text
    assert "If the user declines charts" in text
    assert "Evidence is generated by the framework; the narrative is authored by the Agent" in text


def test_research_report_writer_skill_requires_institutional_report_structure() -> None:
    skill = Path("agent/skills/research-report-writer.md")

    text = skill.read_text(encoding="utf-8")

    assert "Institutional Report Standard" in text
    assert "Executive Snapshot" in text
    assert "30-second investor view" in text
    assert "3-minute research view" in text
    assert "professional appendix" in text
    assert "trust and audit status" in text
    assert "risks near the decision" in text
    assert "metric scorecard" in text
    assert "message-first" in text


def test_open_xquant_router_skill_routes_quant_tasks_to_leaf_skills() -> None:
    skill = Path("agent/skills/open-xquant.md")

    text = skill.read_text(encoding="utf-8")

    assert "name: open-xquant" in text
    assert "Use when" in text
    assert "quantitative research" in text
    assert "Router Contract" in text
    assert "Do not run other `oxq` commands" in text
    assert "Do not write report files directly" in text
    assert "minimal runner/workspace commands" in text
    assert "`research init --sdk`" in text
    assert "Install And Upgrade Questions" in text
    assert "installed Agents must not depend on that file" in text
    assert "<runner> agent status" in text
    assert "ask the user whether charts are needed" in text
    assert "report-chart-builder` if the user wants figures" in text
    for leaf_skill in [
        "strategy-builder",
        "quant-research",
        "spec-auditor",
        "strategy-monitor",
        "report-chart-builder",
        "experiment-comparator",
        "research-report-writer",
        "research-report-reviewer",
        "performance-reviewer",
        "factor-evaluator",
        "factor-screening",
        "parameter-tuner",
        "component-creator",
        "live-trader",
    ]:
        assert leaf_skill in text

def test_spec_auditor_skill_documents_source_trace_gate() -> None:
    skill = Path("agent/skills/spec-auditor.md")

    text = skill.read_text(encoding="utf-8")

    assert "name: spec-auditor" in text
    assert "confirmed" in text
    assert "default" in text
    assert "unconfirmed" in text
    assert "last successful `oxq spec validate`" in text
    assert "blocks backtest" in text
    assert "group related fields" in text


def test_experiment_comparator_skill_documents_cross_run_outputs() -> None:
    skill = Path("agent/skills/experiment-comparator.md")

    text = skill.read_text(encoding="utf-8")

    assert "name: experiment-comparator" in text
    assert "comparisons/" in text
    assert ".open-xquant/workspace.yaml" in text
    assert "paths.comparisons_dir" in text
    assert "paths.comparison_registry" in text
    assert "spec_diff.yaml" in text
    assert "metrics_comparison.json" in text
    assert "comparison_report.md" in text
    assert "equity_overlay" in text
    assert "drawdown_overlay" in text
    assert "metrics_bar" in text
    assert "metrics.json" in text


def test_open_xquant_router_resumes_writer_after_chart_builder_before_rendering() -> None:
    text = Path("agent/skills/open-xquant.md").read_text(encoding="utf-8")

    start = text.index('- "Write the final report":')
    end = text.index('- "Review whether this can be traded":')
    sequence = text[start:end]

    chart_step = sequence.index("`report-chart-builder` if the user wants figures")
    resume_step = sequence.index("resume `research-report-writer`")
    render_step = sequence.index("render HTML")

    assert chart_step < resume_step < render_step


def test_research_report_reviewer_skill_covers_semantic_report_qa() -> None:
    skill = Path("agent/skills/research-report-reviewer.md")

    text = skill.read_text(encoding="utf-8")

    assert "research-report-reviewer" in text
    assert "decision_policy" in text
    assert "REJECT" in text
    assert "WATCHLIST" in text
    assert "PAPER TRADING CANDIDATE" in text
    assert "audit" in text
    assert "robustness" in text
    assert "numeric_claim_unverified" in text
    assert "facts registry" in text
    assert "CJK" in text
    assert "chart" in text
    assert "do not rewrite" in text.lower()


def test_quant_reporter_routes_final_report_through_writer_skill() -> None:
    reporter = Path("agent/opencode/agents/quant-reporter.md").read_text(encoding="utf-8")
    command = Path("agent/opencode/commands/quant-report.md").read_text(encoding="utf-8")

    combined = reporter + "\n" + command

    assert "research-report-writer" in combined
    assert "research-report-reviewer" in combined
    assert "render `research_report.html` again" in combined
    assert "render_markdown_html_report" in combined
    assert "oxq report asset add-batch" in combined
    assert "Final report QA" in combined
    assert "oxq report qa" in combined
    assert "report_evidence.md" not in combined
    assert "oxq report write" not in combined


def test_opencode_quant_research_includes_final_report_qa_gate() -> None:
    text = Path("agent/skills/quant-research.md").read_text(encoding="utf-8")

    assert "Before final report writing, ask the user whether chart assets are needed" in text
    assert "If the user wants charts" in text
    assert "report-chart-builder" in text
    assert "Final report QA" in text
    assert "oxq report qa" in text
    assert "research-report-reviewer" in text
    assert "render `research_report.html`" in text
    assert "Markdown/HTML image counts" in text
    assert "configured end date" in text
    assert "effective last trading day" in text
    assert ".open-xquant/workspace.yaml" in text
    assert "paths.final_dir" in text


def test_strategy_builder_includes_lifecycle_and_spec_auditor_gates() -> None:
    text = Path("agent/skills/strategy-builder.md").read_text(encoding="utf-8")

    assert "Experiment Lifecycle Check" in text
    assert "research_report.md" in text
    assert "research_bias_audit.json" in text
    assert "robustness.json" in text
    assert "Skip robustness sub-runs" in text
    assert "_cost_x2" in text
    assert "spec-auditor" in text
    assert "runs/final" in text
    assert ".open-xquant/workspace.yaml" in text
    assert "paths.final_dir" in text


def test_quant_research_and_monitor_disclose_lifecycle_final_and_robustness_runs() -> None:
    quant_research = Path("agent/skills/quant-research.md").read_text(encoding="utf-8")
    strategy_monitor = Path("agent/skills/strategy-monitor.md").read_text(encoding="utf-8")

    assert "Experiment Lifecycle Check" in quant_research
    assert "Skip robustness sub-runs" in quant_research
    assert "runs/final" in quant_research
    assert "mark it as final" in quant_research
    assert "_cost_x2" in strategy_monitor
    assert "created sub-run directory" in strategy_monitor


def test_agent_guide_is_install_only_and_points_to_router_skill() -> None:
    text = Path("docs/agent-guide.md").read_text(encoding="utf-8")

    assert "skill 单一来源是 `agent/skills/*.md`" in text
    assert "不要维护 `agent/opencode/skills/`" in text
    assert "`skills.paths`" in text
    assert "open-xquant router skill" in text
    assert "current worktree runner" in text
    assert "preferred_runner" in text
    assert "`~/.config/open-xquant/agent-install.json`" in text
    assert "SDK bundle" in text
    assert "用户任务路由" not in text
    assert "Spec 最小模板" not in text
    assert "CLI 速查" not in text
    assert "策略想法或新策略" not in text


def test_human_guide_first_use_prompt_uses_runnable_status_command() -> None:
    text = Path("docs/human-guide.md").read_text(encoding="utf-8")

    assert "安装后运行 uv run oxq agent status" in text
    assert "安装后运行 oxq agent status" not in text


def test_examples_do_not_reference_removed_report_write_command() -> None:
    combined = "\n".join(path.read_text(encoding="utf-8") for path in Path("examples").rglob("*.py"))

    assert "oxq report write" not in combined


def test_readme_workflows_do_not_reference_removed_report_write_command() -> None:
    text = Path("README.md").read_text(encoding="utf-8")

    assert "oxq report write" not in text


def test_strategy_builder_skill_prepares_artifacts_for_professional_reports() -> None:
    skill = Path("agent/skills/strategy-builder.md")

    text = skill.read_text(encoding="utf-8")

    assert "Report Artifact Readiness" in text
    assert "metrics.json" in text
    assert "equity_curve.csv" in text
    assert "benchmark_curve.csv" in text
    assert "trades.csv" in text
    assert "positions.csv" in text
    assert "orders.csv" in text
    assert "target_weights.csv" in text
    assert "robustness.json" in text
    assert "cost_multiplier" in text
    assert "parameter_perturbation" in text
    assert "regime_analysis" in text
    assert "professional report" in text
