from __future__ import annotations

import json
from pathlib import Path


def test_report_chart_builder_skill_documents_chart_asset_workflow() -> None:
    skill = Path("agent/skills/report-chart-builder.md")

    text = skill.read_text(encoding="utf-8")

    assert "report-chart-builder" in text
    assert "discuss chart requirements" in text
    assert "plotting Python" in text
    assert "report_assets/figures" in text
    assert "report_assets/scripts" in text
    assert "oxq report asset add" in text
    assert "oxq report asset add-batch" in text
    assert "source_artifacts" in text
    assert "research_report.md" in text
    assert "research_report.html" in text
    assert "research-report-writer" in text
    assert "oxq report write" not in text
    assert "report_evidence.md" not in text
    assert "Do not modify metrics" in text
    assert "Do not modify audit" in text
    assert "CJK font" in text
    assert "default to English labels" in text
    assert "non-empty" in text
    assert "dimensions" in text
    assert "manifest" in text


def test_opencode_quant_reporter_can_write_html_and_report_assets() -> None:
    config = json.loads(Path("agent/opencode/opencode.json").read_text(encoding="utf-8"))

    write_permissions = config["agents"]["quant-reporter"]["permissions"]["write"]

    assert "runs/*/research_report.md" in write_permissions
    assert "runs/*/research_report.html" in write_permissions
    assert "runs/*/report_assets/**" in write_permissions
    assert "runs/*/report_evidence.md" not in write_permissions
    assert "report_write" not in config["agents"]["quant-reporter"]["tools"]


def test_opencode_bundle_references_single_source_skills() -> None:
    config = json.loads(Path("agent/opencode/opencode.json").read_text(encoding="utf-8"))

    for skill_path in config["skills"].values():
        assert skill_path.startswith("../skills/")
        assert (Path("agent/opencode") / skill_path).resolve().exists()
    assert not Path("agent/opencode/skills").exists()


def test_research_report_writer_skill_requires_agent_authored_final_report() -> None:
    skill = Path("agent/skills/research-report-writer.md")

    text = skill.read_text(encoding="utf-8")

    assert "research-report-writer" in text
    assert "research_report.md" in text
    assert "research_report.html" in text
    assert "render_markdown_html_report" in text
    assert "human researcher" in text
    assert "potential investor" in text
    assert "report_evidence.md" not in text
    assert "oxq report write" not in text
    assert "Do not invent evidence" in text
    assert "monthly returns" in text
    assert "positive/negative month counts" in text
    assert "artifact or facts API" in text
    assert "Evidence is generated by the framework; the narrative is authored by the Agent" in text


def test_quant_reporter_routes_final_report_through_writer_skill() -> None:
    reporter = Path("agent/opencode/agents/quant-reporter.md").read_text(encoding="utf-8")
    command = Path("agent/opencode/commands/quant-report.md").read_text(encoding="utf-8")

    combined = reporter + "\n" + command

    assert "research-report-writer" in combined
    assert "render_markdown_html_report" in combined
    assert "oxq report asset add-batch" in combined
    assert "Final report QA" in combined
    assert "oxq report qa" in combined
    assert "report_evidence.md" not in combined
    assert "oxq report write" not in combined


def test_opencode_quant_research_includes_final_report_qa_gate() -> None:
    text = Path("agent/skills/quant-research.md").read_text(encoding="utf-8")

    assert "Final report QA" in text
    assert "oxq report qa" in text
    assert "Markdown/HTML image counts" in text
    assert "configured end date" in text
    assert "effective last trading day" in text


def test_agent_guide_documents_runner_audit_filename_and_report_dates() -> None:
    text = Path("docs/agent-guide.md").read_text(encoding="utf-8")

    assert "skill 单一来源是 `agent/skills/*.md`" in text
    assert "不要维护 `agent/opencode/skills/`" in text
    assert "current worktree runner" in text
    assert "preferred_runner" in text
    assert "`research_bias_audit.json` is the artifact filename" in text
    assert "`audit_research` is the tool/function name" in text
    assert "effective last trading day" in text
    assert "configured end date" in text


def test_examples_do_not_reference_removed_report_write_command() -> None:
    combined = "\n".join(path.read_text(encoding="utf-8") for path in Path("examples").rglob("*.py"))

    assert "oxq report write" not in combined


def test_readme_workflows_do_not_reference_removed_report_write_command() -> None:
    text = Path("README.md").read_text(encoding="utf-8")

    assert "oxq report write" not in text
