"""Data manifest — provenance and integrity metadata for parquet files."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone

UTC = timezone.utc  # Python 3.9 compatible
from pathlib import Path
from typing import Any, Literal


@dataclass
class ManifestVerification:
    """Result of verifying a parquet file against its manifest."""

    status: Literal["real", "mock", "missing", "corrupted"]
    provider: str | None
    detail: str


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def write_manifest(
    parquet_path: Path,
    symbol: str,
    provider: str,
    start: str,
    end: str,
    rows: int,
    extra: dict[str, Any] | None = None,
) -> Path:
    """Compute parquet sha256, write {symbol}.manifest.json, return manifest path."""
    manifest: dict[str, Any] = {
        "symbol": symbol,
        "provider": provider,
        "start": start,
        "end": end,
        "rows": rows,
        "sha256": _sha256(parquet_path),
        "created_at": datetime.now(UTC).isoformat(),
        "extra": extra,
    }
    manifest_path = parquet_path.parent / f"{symbol}.manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
    return manifest_path


def read_manifest(manifest_path: Path) -> dict[str, Any] | None:
    """Read and parse a manifest file. Return None if missing or malformed."""
    try:
        return json.loads(manifest_path.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def verify_manifest(parquet_path: Path) -> ManifestVerification:
    """Read manifest for a parquet file, recompute sha256, return verification result."""
    stem = parquet_path.stem
    manifest_path = parquet_path.parent / f"{stem}.manifest.json"
    data = read_manifest(manifest_path)

    if data is None:
        return ManifestVerification(
            status="missing",
            provider=None,
            detail=f"No manifest found for {parquet_path.name}",
        )

    provider = data.get("provider")

    if provider == "mock":
        return ManifestVerification(
            status="mock",
            provider="mock",
            detail="Data generated by mock provider",
        )

    actual_sha = _sha256(parquet_path)
    expected_sha = data.get("sha256")

    if actual_sha != expected_sha:
        return ManifestVerification(
            status="corrupted",
            provider=provider,
            detail=f"SHA256 mismatch: expected {expected_sha[:16]}..., got {actual_sha[:16]}...",
        )

    return ManifestVerification(
        status="real",
        provider=provider,
        detail=f"Verified {provider} data, {data.get('rows', '?')} rows",
    )
